### PR TITLE
Make code easier to run and read for an external user

### PR DESCRIPTION
**Pull request by MatthieuBizien**
Hi, nice paper :) In the process of reading and executing the code, I made a few changes that you may be interested to port back. It's mostly about initializing the system on the first run, the formatting, and a .gitignore.

### CODE REVIEW

**Review by devzhk — CHANGES_REQUESTED** [review]
Great advice. I will approve the change in `VisionData.py` and `wgan_gp.py`. But I would rather reorganize the code in `cgd_utils.py`, `models.py`, 'optimizers.py' by my self to make it meaningful.

**Review by devzhk — APPROVED** [review]
Good change

**Review by devzhk — APPROVED** [review]
Good change

**Review by devzhk — CHANGES_REQUESTED** [review]
Could you also add figs/ to git ignore file please?

**Review by devzhk — APPROVED** [review]
Nice! Thanks for your contribution.

**Comment by MatthieuBizien** [comment]
> Could you also add figs/ to git ignore file please?

I updated the .gitignore.

> Great advice. I will approve the change in VisionData.py and wgan_gp.py. But I would rather reorganize the code in cgd_utils.py, models.py, 'optimizers.py' by my self to make it meaningful.

The only change is the de-duplication of zero-grad, that was making copy and paste into a notebook painful. Because this PR change a lot of lines (mainly indentation), I encourage you to merge it as soon as possible, because it will be really painful to update it if something else is commited 😅It's much easier to reorganize your code after the merge.

**Review by devzhk — APPROVED** [review]

**Comment by devzhk** [comment]
Alright. I merged the changes.

**Comment by devzhk** [comment]
Merged

**Pull request merged**
